spring.application.name=backend
server.port=8080

### postgres sql config ###
spring.datasource.url=jdbc:postgresql://localhost:5432/fluxgate
spring.datasource.username=postgres
spring.datasource.password=tanay

# Spring Data JPA config #
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Config #
spring.redis.host=localhost
spring.redis.port=6379

